---
title: "prolific.api: List of Available Prescreeners"
author: "Simon Lenau"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: yes
vignette: >
  %\VignetteIndexEntry{prolific.api: List of Available Prescreeners}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  \usepackage[utf8]{inputenc}
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
---

```{r, include = FALSE}
stopifnot(require(knitr))
options(width = 90)
knitr::opts_chunk$set(
    eval = FALSE,
    collapse = !TRUE,
    comment = "#>",
    dev = "jpeg",
    dpi = 100,
    fig.asp = 0.8,
    fig.width = 5,
    out.width = "60%",
    fig.align = "center"
)
library(prolific.api)
library(lenau)
```





**List of available Prescreeners**  
***(Click on the respective row to show all available constraints and R-code snippets)***


`r 
library(data.table)
library(prolific.api)
library(reactable)

# Create API access
prolific_api_access <- api_access(api_token = readLines("~/.prolific_api/ers_prolific_api_token", warn = FALSE))

list_of_prescreeners <- prolific_api_access$.internals$methods$prescreeners()

list_of_prescreeners[, constraints :=
    (lapply(list_of_prescreeners$attributes, function(x) paste0(x$label, collapse = "    ")))]


x <- list_of_prescreeners[!grepl("selectanswer", tolower(cls)), ][1, ]


prescreener_code_fmt <-
    function(x) {
        if ("type" %in% names(x)) {
            if ("min" %in% names(x)) {
                z <- unlist(lapply(x[, .SD, .SDcols = c("min", "max")], as.character), recursive = FALSE)

                if (tolower(x$type) == "date") {
                    return(paste0("\"", as.IDate(c(0.2, 0.8) %*% (as.IDate(z))), "\""))
                }

                if (tolower(x$type) == "number") {
                    z <- z[!grepl("(false|true)", tolower(z))]
                    return(mean(as.numeric(z)))
                }

                if (tolower(x$type) %in% c("min", "max")) {
                    z <- z[!grepl("(false|true)", tolower(z))]
                    return(c(c(0.8, 0.2) %*% (as.numeric(z))))
                }

                return(z)
            } else {
                if (tolower(x$type) == "list") {
                    if (grepl("(white|black)_list", tolower(x$name))) {
                        # set.seed(2)
                        # return(paste0("list(", paste0("\"", vapply(1:, function(i) {
                        #   paste0(sample(c(0:9, letters), 24, replace = TRUE), collapse = "")
                        # }, "a"), "\"", collapse = ","), ")"))
                        return("list('&lt;respondents_prolific_id_1&gt;','&lt;respondents_prolific_id_2&gt;')")
                    }
                }
                if (tolower(x$name == "blocked_studies")) {
                    return("list('&lt;internal_study_name_or_id_1&gt;','&lt;internal_study_name_or_id_2&gt;')")
                }
            }
        }
    }


constraint_fmt <-
    function(x, ncol = 4) {
        title <- x$title
        cls <- x$cls

        labels <- x$attributes[[1]]$label


        if (length(labels) >= 10) {
            labels <- sort(labels)
        }
        nrow <- ceiling(length(labels) / ncol)
        tbl <- matrix(c(labels, rep("", nrow * ncol - length(labels))), ncol = ncol, byrow = TRUE)
        colnames(tbl) <- paste0("V", 1:ncol)

        example_code_intro_pre <-
            paste0(
                "<p style=\"margin-left: 3px; margin-right: 3px;font-size:90%;font-family:Verdana;color:#1f1f2e\">",
                "Example Code for selecting participants",
                c(
                    if (grepl("SelectAnswer", cls)) {
                        paste0(" where '", title, "' is")
                    },
                    if (grepl("custom(white|black)list", tolower(cls))) {
                        paste0(" using a ")
                    }
                ),
                " '"
            )

        example_code_intro_post <-
            paste0(
                "':</p>"
            )

        example_code_pre <- paste0(
            "<p style=\"margin-left: 3px; margin-right: 3px; background-color:#999999;text-align:center;font-size:90%;color:#1affff;font-family:Courier New\">",
            "prolific_prescreener(",
            "title = \"", title, "\", "
        )
        example_code_post <- paste0(
            ")",
            "</p>"
        )

        out_list <- lapply(
            1:ncol(tbl),
            function(i) {
                colDef(
                    html = TRUE,
                    resizable = TRUE,
                    name = "",
                    show = TRUE,
                    details = function(index) {
                        if (tbl[index, i] != "") {
                            pos <- min(which(x$attributes[[1]]$label %in% tbl[index, i]))
                            paste0(
                                example_code_intro_pre,
                                as.character(tbl[index, i]),
                                example_code_intro_post,
                                example_code_pre,
                                "\"", as.character(tbl[index, i]), "\"",
                                if (!grepl("SelectAnswer", cls)) {
                                    paste0(
                                        " = ",
                                        prescreener_code_fmt(x$attributes[[1]][pos, ])
                                    )
                                },
                                example_code_post
                            )
                        } else {
                            NULL
                        }
                    }
                )
            }
        )

        names(out_list) <- colnames(tbl)

        reactable(tbl,
            columns = out_list,
            borderless = TRUE,
            outlined = FALSE,
            compact = TRUE,
            searchable = !TRUE,
            columnGroups = list(colGroup(
                html = TRUE,
                name = paste0(
                    "Possible constraints",
                    if (!is.null(title)) {
                        paste0(" for prescreener '", title, "'")
                    },
                    "<br>",
                    "(Click on the respective constraint to show example R-Code)"
                ),
                columns = names(out_list),
                align = "left"
            )),
            theme = reactableTheme(borderWidth = "0px", backgroundColor = "#f2f2f2", color = "#000000"),
            striped = FALSE,
            minRows = nrow,
            defaultPageSize = nrow
        )
    }

html <- function(x, inline = FALSE) {
    container <- if (inline) htmltools::span else htmltools::div
    container(dangerouslySetInnerHTML = list("__html" = x))
}

reactable(list_of_prescreeners,
    searchable = TRUE,
    showSortable = TRUE,
    filterable = !TRUE,
    highlight = TRUE,
    striped = !TRUE,
    compact = TRUE,
    minRows = nrow(list_of_prescreeners),
    defaultPageSize = nrow(list_of_prescreeners),
    columns = list(
        title = colDef(name = "Prescreener title", html = TRUE, resizable = TRUE, minWidth = 200),
        category = colDef(
            name = "Category", show = TRUE, maxWidth = 2000, minWidth = 100,
            style = function(value) {
                list("color" = "lightgreen")
            }
        ),
        subcategory = colDef(name = "Subcategory", show = TRUE, maxWidth = 1010, minWidth = 100),
        constraints = colDef(show = !TRUE, searchable = TRUE),
        id = colDef(show = FALSE),
        cls = colDef(show = FALSE),
        attributes = colDef(show = FALSE)
    ),
    # if there exists a comment, make row expandable
    details = function(index) {
        constraint_fmt(
            list_of_prescreeners[index, ]
        )
    },
    theme = reactableTheme(color = "#000000")
)
`



